# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 53005a435629c82192cebf969f619414555c5bff317825980f4beb4ae57ff7cde74e613257f5d729440d3efbe9dfeb7b1fb708b45cf507dc347b9ea56c4a6976

test:
  secret_key_base: e273c054e205bfb73c7bd12d5340e9da56691319eba0571d59afa431336fcc895eab9b8b8738cb5f820f7ffa278bb6e9478de26ce169ced9a8d22cd9a1235986

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
